# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52afc6ad524bfb0cbf984c2f598cd9312184d479978171642f42356be38b610d7c1d0c45b3bde69a58f081fa874344ac5a4307883d254265d19654653807a1c0

test:
  secret_key_base: cb511994d3aef498da6aa3bbc1d01e7285f390b8f12be3d0cfafb426cb6643ff3aeb7809f2f56e9d3b3841019dfb75a39d6a8b68f5500b68392da9be0fdeaf81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
